package com.lcm.doctorwho.client.models.tardis.decoration;

import com.lcm.doctorwho.AcrossTheGalaxy;
import com.lcm.doctorwho.client.models.interfaces.TileModelOutline;
import com.lcm.doctorwho.utils.ATGUtils;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.client.renderer.GlStateManager;
import net.minecraft.util.ResourceLocation;

public class ModelMonitorToyota extends TileModelOutline {

    ResourceLocation TEX = new ResourceLocation(AcrossTheGalaxy.MODID, "textures/blocks/monitor_toyota.png");

    ModelRenderer Monitor1;
    ModelRenderer Monitor2;
    ModelRenderer Monitor3;
    ModelRenderer Monitor4;
    ModelRenderer Monitor5;
    ModelRenderer Monitor6;
    ModelRenderer Monitor7;
    ModelRenderer Monitor8;
    ModelRenderer Monitor9;
    ModelRenderer Monitor10;
    ModelRenderer Monitor11;
    ModelRenderer Monitor12;
    ModelRenderer Monitor13;
    ModelRenderer Monitor14;
    ModelRenderer Monitor15;
    ModelRenderer Monitor16;
    ModelRenderer Monitor17;
    ModelRenderer Monitor18;
    ModelRenderer Monitor19;
    ModelRenderer Monitor20;
    ModelRenderer Monitor21;
    ModelRenderer Monitor22;
    ModelRenderer Monitor23;
    ModelRenderer Monitor24;
    ModelRenderer Monitor25;
    ModelRenderer Monitor26;
    ModelRenderer Monitor27;
    ModelRenderer Monitor28;
    ModelRenderer Monitor29;

    public ModelMonitorToyota()
    {
        textureWidth = 60;
        textureHeight = 60;

        Monitor1 = new ModelRenderer(this, 24, 0);
        Monitor1.addBox(-2F, -7F, -1F, 4, 4, 1);
        Monitor1.setRotationPoint(0F, 23F, 8F);
        Monitor1.setTextureSize(60, 60);
        Monitor1.mirror = true;
        ATGUtils.setRotation(Monitor1, 0F, 0F, 0F);
        Monitor2 = new ModelRenderer(this, 0, 22);
        Monitor2.addBox(5F, -13F, -9F, 1, 6, 1);
        Monitor2.setRotationPoint(0F, 23F, 6F);
        Monitor2.setTextureSize(60, 60);
        Monitor2.mirror = true;
        ATGUtils.setRotation(Monitor2, 0F, 0F, 0F);
        Monitor3 = new ModelRenderer(this, 6, 23);
        Monitor3.addBox(-6F, -7.5F, -9F, 12, 1, 1);
        Monitor3.setRotationPoint(0F, 23F, 6F);
        Monitor3.setTextureSize(60, 60);
        Monitor3.mirror = true;
        ATGUtils.setRotation(Monitor3, 0F, 0F, 0F);
        Monitor4 = new ModelRenderer(this, 54, 0);
        Monitor4.addBox(0F, 0.5F, -1F, 1, 1, 1);
        Monitor4.setRotationPoint(6F, 14F, -3F);
        Monitor4.setTextureSize(60, 60);
        Monitor4.mirror = true;
        ATGUtils.setRotation(Monitor4, 0F, -0.5235988F, 0F);
        Monitor5 = new ModelRenderer(this, 6, 23);
        Monitor5.addBox(-6F, -14F, -9F, 12, 1, 1);
        Monitor5.setRotationPoint(0F, 23F, 6F);
        Monitor5.setTextureSize(60, 60);
        Monitor5.mirror = true;
        ATGUtils.setRotation(Monitor5, 0F, 0F, 0F);
        Monitor6 = new ModelRenderer(this, 26, 13);
        Monitor6.addBox(-5F, -13F, -8F, 10, 6, 0);
        Monitor6.setRotationPoint(0F, 23F, 6F);
        Monitor6.setTextureSize(60, 60);
        Monitor6.mirror = true;
        ATGUtils.setRotation(Monitor6, 0F, 0F, 0F);
        Monitor7 = new ModelRenderer(this, 6, 12);
        Monitor7.addBox(-1.5F, -11.5F, -8F, 3, 3, 1);
        Monitor7.setRotationPoint(0F, 23F, 6F);
        Monitor7.setTextureSize(60, 60);
        Monitor7.mirror = true;
        ATGUtils.setRotation(Monitor7, 0F, 0F, 0F);
        Monitor8 = new ModelRenderer(this, 34, 0);
        Monitor8.addBox(0.5F, 0.5F, 7F, 1, 1, 3);
        Monitor8.setRotationPoint(0F, 12F, 0F);
        Monitor8.setTextureSize(60, 60);
        Monitor8.mirror = true;
        ATGUtils.setRotation(Monitor8, -0.6108652F, 0F, 0F);
        Monitor9 = new ModelRenderer(this, 42, 0);
        Monitor9.addBox(1.5F, -1F, 0F, 0, 1, 2);
        Monitor9.setRotationPoint(0F, 13.5F, 0F);
        Monitor9.setTextureSize(60, 60);
        Monitor9.mirror = true;
        ATGUtils.setRotation(Monitor9, 0.6981317F, 0F, 0F);
        Monitor10 = new ModelRenderer(this, 0, 12);
        Monitor10.addBox(-1F, -12F, -8F, 2, 4, 1);
        Monitor10.setRotationPoint(0F, 23F, 6F);
        Monitor10.setTextureSize(60, 60);
        Monitor10.mirror = true;
        ATGUtils.setRotation(Monitor10, 0F, 0F, 0F);
        Monitor11 = new ModelRenderer(this, 0, 17);
        Monitor11.addBox(-2F, -11F, -8F, 4, 2, 1);
        Monitor11.setRotationPoint(0F, 23F, 6F);
        Monitor11.setTextureSize(60, 60);
        Monitor11.mirror = true;
        ATGUtils.setRotation(Monitor11, 0F, 0F, 0F);
        Monitor12 = new ModelRenderer(this, 6, 23);
        Monitor12.addBox(-6F, -7F, -9F, 12, 1, 1);
        Monitor12.setRotationPoint(0F, 23F, 6F);
        Monitor12.setTextureSize(60, 60);
        Monitor12.mirror = true;
        ATGUtils.setRotation(Monitor12, 0F, 0F, 0F);
        Monitor13 = new ModelRenderer(this, 0, 22);
        Monitor13.addBox(-6F, -13F, -9F, 1, 6, 1);
        Monitor13.setRotationPoint(0F, 23F, 6F);
        Monitor13.setTextureSize(60, 60);
        Monitor13.mirror = true;
        ATGUtils.setRotation(Monitor13, 0F, 0F, 0F);
        Monitor14 = new ModelRenderer(this, 24, 5);
        Monitor14.addBox(0F, -3F, -1.5F, 1, 4, 1);
        Monitor14.setRotationPoint(6F, 14F, -3F);
        Monitor14.setTextureSize(60, 60);
        Monitor14.mirror = true;
        ATGUtils.setRotation(Monitor14, 0F, -0.5235988F, 0F);
        Monitor15 = new ModelRenderer(this, 54, 0);
        Monitor15.addBox(6F, -8.5F, -9F, 1, 1, 1);
        Monitor15.setRotationPoint(0F, 23F, 6F);
        Monitor15.setTextureSize(60, 60);
        Monitor15.mirror = true;
        ATGUtils.setRotation(Monitor15, 0F, 0F, 0F);
        Monitor16 = new ModelRenderer(this, 54, 0);
        Monitor16.addBox(6F, -12.5F, -9F, 1, 1, 1);
        Monitor16.setRotationPoint(0F, 23F, 6F);
        Monitor16.setTextureSize(60, 60);
        Monitor16.mirror = true;
        ATGUtils.setRotation(Monitor16, 0F, 0F, 0F);
        Monitor17 = new ModelRenderer(this, 54, 0);
        Monitor17.addBox(0F, -3.5F, -1F, 1, 1, 1);
        Monitor17.setRotationPoint(6F, 14F, -3F);
        Monitor17.setTextureSize(60, 60);
        Monitor17.mirror = true;
        ATGUtils.setRotation(Monitor17, 0F, -0.5235988F, 0F);
        Monitor18 = new ModelRenderer(this, 54, 0);
        Monitor18.addBox(-7F, -12.5F, -9F, 1, 1, 1);
        Monitor18.setRotationPoint(0F, 23F, 6F);
        Monitor18.setTextureSize(60, 60);
        Monitor18.mirror = true;
        ATGUtils.setRotation(Monitor18, 0F, 0F, 0F);
        Monitor19 = new ModelRenderer(this, 54, 0);
        Monitor19.addBox(-7F, -8.5F, -9F, 1, 1, 1);
        Monitor19.setRotationPoint(0F, 23F, 6F);
        Monitor19.setTextureSize(60, 60);
        Monitor19.mirror = true;
        ATGUtils.setRotation(Monitor19, 0F, 0F, 0F);
        Monitor20 = new ModelRenderer(this, 54, 0);
        Monitor20.addBox(-1F, -3.5F, -1F, 1, 1, 1);
        Monitor20.setRotationPoint(-6F, 14F, -3F);
        Monitor20.setTextureSize(60, 60);
        Monitor20.mirror = true;
        ATGUtils.setRotation(Monitor20, 0F, 0.5235988F, 0F);
        Monitor21 = new ModelRenderer(this, 24, 5);
        Monitor21.addBox(-1F, -3F, -1.5F, 1, 4, 1);
        Monitor21.setRotationPoint(-6F, 14F, -3F);
        Monitor21.setTextureSize(60, 60);
        Monitor21.mirror = true;
        ATGUtils.setRotation(Monitor21, 0F, 0.5235988F, 0F);
        Monitor22 = new ModelRenderer(this, 54, 0);
        Monitor22.addBox(-1F, 0.5F, -1F, 1, 1, 1);
        Monitor22.setRotationPoint(-6F, 14F, -3F);
        Monitor22.setTextureSize(60, 60);
        Monitor22.mirror = true;
        ATGUtils.setRotation(Monitor22, 0F, 0.5235988F, 0F);
        Monitor23 = new ModelRenderer(this, 5, 27);
        Monitor23.addBox(-1F, -11F, -7F, 2, 2, 1);
        Monitor23.setRotationPoint(0F, 23F, 6F);
        Monitor23.setTextureSize(60, 60);
        Monitor23.mirror = true;
        ATGUtils.setRotation(Monitor23, 0F, 0F, 0F);
        Monitor24 = new ModelRenderer(this, 46, 0);
        Monitor24.addBox(-1.5F, -10.5F, -7F, 3, 1, 1);
        Monitor24.setRotationPoint(0F, 23F, 6F);
        Monitor24.setTextureSize(60, 60);
        Monitor24.mirror = true;
        ATGUtils.setRotation(Monitor24, 0F, 0F, 0F);
        Monitor25 = new ModelRenderer(this, 36, 5);
        Monitor25.addBox(-5F, -13F, -8.95F, 10, 6, 0);
        Monitor25.setRotationPoint(0F, 23F, 6F);
        Monitor25.setTextureSize(60, 60);
        Monitor25.mirror = true;
        ATGUtils.setRotation(Monitor25, 0F, 0F, 0F);
        Monitor26 = new ModelRenderer(this, 34, 22);
        Monitor26.addBox(-3F, -12.5F, -8.7F, 6, 5, 1);
        Monitor26.setRotationPoint(0F, 23F, 6F);
        Monitor26.setTextureSize(60, 60);
        Monitor26.mirror = true;
        ATGUtils.setRotation(Monitor26, 0F, 0F, 0F);
        Monitor27 = new ModelRenderer(this, 14, 12);
        Monitor27.addBox(-3F, -3.5F, -1F, 3, 5, 1);
        Monitor27.setRotationPoint(-3F, 14F, -1.7F);
        Monitor27.setTextureSize(60, 60);
        Monitor27.mirror = true;
        ATGUtils.setRotation(Monitor27, 0F, -0.0872665F, 0F);
        Monitor28 = new ModelRenderer(this, 14, 12);
        Monitor28.addBox(0F, -3.5F, -1F, 3, 5, 1);
        Monitor28.setRotationPoint(3F, 14F, -1.7F);
        Monitor28.setTextureSize(60, 60);
        Monitor28.mirror = true;
        ATGUtils.setRotation(Monitor28, 0F, 0.0872665F, 0F);
        Monitor29 = new ModelRenderer(this, 0, 0);
        Monitor29.addBox(-1F, 0F, 0F, 2, 2, 10);
        Monitor29.setRotationPoint(0F, 12F, 0F);
        Monitor29.setTextureSize(60, 60);
        Monitor29.mirror = true;
        ATGUtils.setRotation(Monitor29, -0.6108652F, 0F, 0F);
    }

    @Override
    public void render(float scale) {
        GlStateManager.pushMatrix();
        GlStateManager.translate(0.4,-0.5,0.1);
        Monitor1.render(scale);
        Monitor2.render(scale);
        Monitor3.render(scale);
        Monitor4.render(scale);
        Monitor5.render(scale);
        Monitor6.render(scale);
        Monitor7.render(scale);
        Monitor8.render(scale);
        Monitor9.render(scale);
        Monitor10.render(scale);
        Monitor11.render(scale);
        Monitor12.render(scale);
        Monitor13.render(scale);
        Monitor14.render(scale);
        Monitor15.render(scale);
        Monitor16.render(scale);
        Monitor17.render(scale);
        Monitor18.render(scale);
        Monitor19.render(scale);
        Monitor20.render(scale);
        Monitor21.render(scale);
        Monitor22.render(scale);
        Monitor23.render(scale);
        Monitor24.render(scale);
        Monitor25.render(scale);
        Monitor26.render(scale);
        Monitor27.render(scale);
        Monitor28.render(scale);
        Monitor29.render(scale);
        GlStateManager.popMatrix();
    }

    @Override
    public ResourceLocation getTexture() {
        return TEX;
    }
}
